import {NetworkTypes} from '@libs/constants';

// TODO add RPC URLs from ENVs
const networkInfo = {
  [`${NetworkTypes.ethereum_mainnet}`]: {
    color: '#0E76FD',
    disabled: false,
    exchange_enabled: true,
    faucet_url: null,
    rpc_url: '',
    name: 'Ethereum',
    value: NetworkTypes.ethereum_mainnet,
  },
  [`${NetworkTypes.ropsten}`]: {
    color: '#ff4a8d',
    disabled: false,
    exchange_enabled: false,
    rpc_url: '',
    faucet_url: `http://faucet.metamask.io/`,
    name: 'Ropsten',
    testnet: true,
    value: NetworkTypes.ropsten,
  },
  [`${NetworkTypes.kovan}`]: {
    color: '#7057ff',
    disabled: false,
    exchange_enabled: false,
    rpc_url: '',
    faucet_url: `https://faucet.kovan.network/`,
    name: 'Kovan',
    testnet: true,
    value: NetworkTypes.kovan,
  },
  [`${NetworkTypes.rinkeby}`]: {
    color: '#f6c343',
    disabled: false,
    exchange_enabled: false,
    rpc_url: '',
    faucet_url: 'https://faucet.rinkeby.io/',
    name: 'Rinkeby',
    testnet: true,
    value: NetworkTypes.rinkeby,
  },
  [`${NetworkTypes.goerli}`]: {
    color: '#f6c343',
    disabled: false,
    exchange_enabled: false,
    rpc_url: '',
    faucet_url: 'https://goerli-faucet.slock.it/',
    name: 'Goerli',
    testnet: true,
    value: NetworkTypes.goerli,
  },
  [`${NetworkTypes.arbitrum}`]: {
    color: '#2D374B',
    disabled: false,
    exchange_enabled: false,
    rpc_url: '',
    faucet_url: `https://faucet.kovan.network/`,
    layer2: true,
    name: 'Arbitrum',
    value: NetworkTypes.arbitrum,
  },
  [`${NetworkTypes.optimism}`]: {
    color: '#FF4040',
    disabled: false,
    exchange_enabled: false,
    rpc_url: '',
    faucet_url: `https://faucet.kovan.network/`,
    layer2: true,
    name: 'Optimism',
    value: NetworkTypes.optimism,
  },
  [`${NetworkTypes.polygon}`]: {
    color: '#8247E5',
    disabled: false,
    exchange_enabled: false,
    rpc_url: '',
    faucet_url: `https://faucet.kovan.network/`,
    layer2: true,
    longName: 'Polygon (Matic)',
    name: 'Polygon',
    value: NetworkTypes.polygon,
  },
  [`${NetworkTypes.binance_mainnet}`]: {
    color: '#8247E5',
    disabled: false,
    exchange_enabled: false,
    rpc_url: '',
    layer2: false,
    longName: 'Binance Smart Chain',
    name: 'BNB Smart Chain',
    value: NetworkTypes.binance_mainnet,
  },
  [`${NetworkTypes.binance_testnet}`]: {
    color: '#8247E5',
    disabled: false,
    exchange_enabled: false,
    rpc_url: '',
    layer2: false,
    longName: 'Binance Testnet',
    name: 'BNB Testnet',
    value: NetworkTypes.binance_testnet,
  },
  [`${NetworkTypes.solana_mainnet}`]: {
    color: '#8247E5',
    disabled: false,
    exchange_enabled: false,
    rpc_url: '',
    layer2: false,
    longName: 'Solana Mainnet',
    name: 'Solana',
    value: NetworkTypes.solana_mainnet,
  },
  [`${NetworkTypes.solana_testnet}`]: {
    color: '#8247E5',
    disabled: false,
    exchange_enabled: false,
    rpc_url: '',
    layer2: false,
    longName: 'Solana Testnet',
    name: 'Solana Testnet',
    value: NetworkTypes.solana_testnet,
  },
  [`${NetworkTypes.bitcoin}`]: {
    color: '#8247E5',
    disabled: false,
    exchange_enabled: false,
    rpc_url: '',
    layer2: false,
    longName: 'Bitcoin',
    name: 'Bitcoin',
    value: NetworkTypes.bitcoin,
  },
};

export default networkInfo;
